package dev.shadowsoffire.placebo.registry;

import com.mojang.serialization.MapCodec;

import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.storage.loot.LootContext;

/**
 * Fabric replacement for NeoForge's {@code net.neoforged.neoforge.common.loot.IGlobalLootModifier}.
 * <p>
 * Defines the runtime contract a global loot modifier must implement. Fabric has no global-loot-modifier registry; the
 * <i>serializer</i> {@link MapCodec} is registered through {@link DeferredHelper#lootModifier} into {@link LootModifierRegistry},
 * and {@link LootModifierManager} loads {@code data/<ns>/loot_modifiers/*.json} entries and applies the registered modifiers
 * (in {@link #priority()} order) from a {@code LootTableEvents.MODIFY_DROPS} listener, which provides the post-roll drop list
 * and {@link LootContext} matching this method's parameters.
 * <p>
 * The NeoForge-only static dispatch codecs ({@code DIRECT_CODEC}/{@code CONDITIONAL_CODEC}, which referenced
 * {@code NeoForgeRegistries} and {@code ConditionalOps}) are intentionally omitted here; the loot subsystem builds the dispatch
 * codec from {@link LootModifierRegistry#dispatchCodec()} instead.
 */
public interface IGlobalLootModifier {

    /**
     * The canonical "default" priority for a loot modifier.
     */
    int DEFAULT_PRIORITY = 1000;

    /**
     * Applies this modifier to the list of generated loot. Implementations are responsible for evaluating their own
     * conditions.
     *
     * @param generatedLoot The list of {@link ItemStack}s that will be dropped, generated by the loot table.
     * @param context       The {@link LootContext}, identical to what is passed to loot tables.
     * @return The modified loot drops.
     */
    ObjectArrayList<ItemStack> apply(ObjectArrayList<ItemStack> generatedLoot, LootContext context);

    /**
     * {@return the registered serializer codec for this modifier}.
     */
    MapCodec<? extends IGlobalLootModifier> codec();

    /**
     * {@return the priority of this loot modifier}. Modifiers with a higher priority are applied first; equal priorities are
     * applied in an undefined order. Read from JSON, never hardcoded.
     */
    int priority();

}
